apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cat-metrics
spec:
  endpoints:
    - interval: 30s
      path: /metrics
      port: http
      scheme: http
  selector:
    matchLabels:
      app: cat
