kind: Deployment
apiVersion: apps/v1
metadata:
  name: unicorn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unicorn
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: unicorn
    spec:
      serviceAccountName: unicorn
      securityContext:
        runAsUser: 1000
      containers:
        - resources: {}
          readinessProbe:
            httpGet:
              path: /readyz
              port: 5000
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          name: unicorn
          livenessProbe:
            httpGet:
              path: /livez
              port: 5000
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: animalsdb
                  key: database-user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: animalsdb
                  key: database-password
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: animalsdb
                  key: database-name
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          imagePullPolicy: Always
          terminationMessagePolicy: File
          envFrom:
            - configMapRef:
                name: cat
          image: 'image-registry.openshift-image-registry.svc:5000/unicorns/unicorns:latest'
      serviceAccount: unicorn
